name: no-time-to-explain

services:
  app:
    image: taiidani/no-time-to-explain:latest
    restart: unless-stopped
    ports:
      - 3502:3000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SENTRY_ENVIRONMENT: "prod"
      SENTRY_DSN: "https://7fd4c058e6685608ada24d63281f6d59@o55858.ingest.us.sentry.io/4507279390539776"
      CMD_TZ: "EDT"
      PORT: "3000"
      URL: "https://no-time-to-explain.taiidani.com"
      DB_TYPE: "postgres"
      REDIS_HOST: redis.no-time-to-explain_default
      REDIS_PORT: "6379"
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres:5432/no-time-to-explain?sslmode=disable"
      DISCORD_TOKEN: "${NTTE_DISCORD_TOKEN}"
      DISCORD_CLIENT_ID: "${NTTE_DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${NTTE_DISCORD_CLIENT_SECRET}"

      # no-time-to-explain: https://discord.com/channels/372591705754566656/1341142254902837380
      # bot-stuff: https://discord.com/channels/570720951373922304/651857324658524181
      # bungie-tweets: https://discord.com/channels/570720951373922304/715987686678200320
      BLUESKY_FEED_CHANNEL_ID: "715987686678200320"

  postgres:
    image: postgres:17
    user: "977:988"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: no-time-to-explain
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../data/no-time-to-explain/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d no-time-to-explain"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    shm_size: 256mb

  redis:
    image: redis:8
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - ./data/redis:/data
