discovery:
  instrument:
    - open_ports: 3000
  exclude_services:
    - container_name: "monitoring.*"
    - container_name: "grafana.*"
    - container_name: "alloy.*"
    - container_name: "homepage.*"

attributes:
  container:
    enable: true
