name: deploy
description: "Standardized deployment logic for hashicorp/taiidani services"

inputs:
  artifact:
    required: true
    description: "The artifact identifier, such as a downloadable binary or Docker image name"
  jobspec:
    required: true
    description: "The path to the jobspec to be rendered"
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v2
      with:
        install: true
        cache: true
        working_directory: ${{ github.action_path }}

    - name: validate
      shell: bash
      working-directory: "${{ github.action_path }}/jobs"
      run: nomad job validate -var 'artifact=${{ inputs.artifact }}' ${{ inputs.jobspec }}

    - name: apply
      shell: bash
      working-directory: "${{ github.action_path }}/jobs"
      run: nomad job run -var 'artifact=${{ inputs.artifact }}' ${{ inputs.jobspec }}
