services:
  plex:
    image: plexinc/pms-docker:1.43.3.10861-07dfddaeb
    x-machines: media
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=claim-KzhcBnt3seFMoXX88t8X
    mem_limit: 1.5g
    mem_reservation: 500m
    volumes:
      - /data/plex/config:/config
      - /data/plex/transcode/temp:/transcode
      - /mnt/unas/content:/data
    x-ports:
      - "32400:32400@host"
