services:
  pms-docker:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=claim-KzhcBnt3seFMoXX88t8X
    volumes:
      - ./data/config:/config
      - ./data/transcode/temp:/transcode
      - nfs_content:/data

volumes:
  nfs_content:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.102.3,nfsvers=3,proto=tcp,nconnect=4,rsize=1048576,noatime,actimeo=600,hard,timeo=100,retrans=3"
      device: ":/var/nfs/shared/Storage/content"
