---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

# Documentation at https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md

title: "Taiidani.com"
subtitle: "Homepage"
# documentTitle: "Welcome" # Customize the browser tab text
icon: "fas fa-home"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: false # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Optional: Proxy / hosting option
proxy:
  # NOT All custom services implements this new option YET. Support will be extended very soon.
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level.

# Optional theming
theme: sui # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
# stylesheet:
#   - "assets/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Optional message
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  # style: "is-warning"
  # title: "Optional message!"
  # icon: "fa fa-exclamation-triangle"
  # content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/taiidani"
  - name: "About Me"
    icon: "fas fa-id-card"
    url: "https://ryannixon.com"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-code-branch"
    items:
      - name: "Guess My Word"
        icon: "fas fa-question-circle"
        subtitle: "Daily guessing game"
        url: "https://guessmyword.xyz/"

  - name: "Management"
    icon: "fas fa-tools"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Terraform Cloud"
        icon: "fas fa-hard-hat"
        subtitle: "Infrastructure management"
        url: "https://app.terraform.io/app/rnd/workspaces"
      - name: "HCP Vault"
        icon: "fas fa-key"
        subtitle: "Secrets management"
        url: "https://rnd.vault.0846e66f-a975-4a88-9e46-6dc6267e9b73.aws.hashicorp.cloud:8200/"
      - name: "Local Nomad"
        icon: "fas fa-box-open"
        subtitle: "Task orchestration"
        url: "http://hashistack.taiidani.com:4646"

  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "Grafana"
        icon: "fas fa-tachometer-alt"
        subtitle: "Metric & Log visualization"
        url: "https://taiidani.grafana.net"
      - name: "Local Traefik"
        icon: "fas fa-sort-amount-down-alt"
        subtitle: "Request routing"
        url: "http://hashistack.taiidani.com:8080"
