default_provider = "onepass"

[providers.onepass]
type = "1password"
vault = "Development"

[secrets]
"WIREGUARD_PRIVATE_KEY"= { provider = "onepass", value = "servarr wireguard private key/credential" }
