name: groceries

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARTIFACT: ${ARTIFACT:-./artifacts/latest.tgz}
    restart: unless-stopped
    ports:
      - 3501:3000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SENTRY_ENVIRONMENT: "prod"
      SENTRY_DSN: "https://b7c94726c8e39af642f012583a6be274@o55858.ingest.us.sentry.io/4508903750434816"
      PORT: "3000"
      URL: "https://groceries.taiidani.com"
      LOG_LEVEL: "info"
      DB_TYPE: "postgres"
      REDIS_HOST: redis.groceries_default
      REDIS_PORT: "6379"
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres:5432/groceries?sslmode=disable"

  postgres:
    image: postgres:17
    user: "977:988"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: groceries
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../data/groceries/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    shm_size: 256mb

  redis:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - ./data/redis:/data
