name: publish binary

on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: "artifact"
      filename:
        required: true
        type: string
    outputs:
      artifact:
        description: "The URL to the published artifact"
        value: ${{ jobs.upload.outputs.artifact }}

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
    outputs:
      artifact: ${{ steps.upload.outputs.artifact }}
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}

      - name: upload
        id: upload
        env:
          BUCKET_URL: "https://rnd-public.sfo3.digitaloceanspaces.com/${{ github.repository }}"
          AWS_REGION: "us-west-2" # Not used, but required for the CLI
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Upload with full filename
          aws s3 cp \
            --endpoint=https://sfo3.digitaloceanspaces.com \
            --acl public-read \
              ./${{ inputs.filename }} s3://rnd-public/${{ github.repository }}/${{ inputs.filename }}

          # Also upload as "latest.tgz" for local development convenience
          aws s3 cp \
            --endpoint=https://sfo3.digitaloceanspaces.com \
            --acl public-read \
              ./${{ inputs.filename }} s3://rnd-public/${{ github.repository }}/latest.tgz

          echo "artifact=${{ env.BUCKET_URL }}/${{ inputs.filename }}" >> "$GITHUB_OUTPUT"
